LANL_aerispico017:
  type: gas_analyzer
  manufacturer: Aeris
  model: Pico
  gases: [CH4_ppm, C2H6_ppb]
  native_hz: 1

LANL_aerisultra321:
  type: gas_analyzer
  manufacturer: Aeris
  model: Ultra
  gases: [CH4_ppm, C2H6_ppm, C3H8_ppm]
  native_hz: 1

LANL_GPS:
  type: gps
  manufacturer: Garmin
  native_hz: 5

LANL_Anem:
  type: met
  manufacturer: Trisonica
  model: Mini
  native_hz: 5

WYO_picarro:
  type: gas_analyzer
  manufacturer: Picarro
  model: G2401
  gases: [CH4_ppm, CO2_ppm, CO_ppm, H2O_ppm]
  native_hz: 0.5

WYO_aerisultra460:
  type: gas_analyzer
  manufacturer: Aeris
  model: Ultra
  gases: [CH4_ppm, C2H6_ppm, C3H8_ppm]
  native_hz: 1

WYO_sprinter:
  type: gps
  native_hz: 1

UOU_LGR:
  type: gas_analyzer
  manufacturer: Los Gatos Research
  model: MGGA
  gases: [CH4_ppm, CO2_ppm]
  native_hz: 1

WYO_PTR-TOF:
  type: gas_analyzer
  manufacturer: Ionicon
  native_hz: null  # no data yet
